---
name: Release OMA

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    name: Release OMA
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build OMA
        run: |
          chmod +x .github/scripts/build.sh
          echo "$GITHUB_REF_NAME" > VERSION
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          .github/scripts/build.sh
          tar cvzf oma-${GITHUB_REF_NAME}.tar.gz oma.pyz composer.json
          ls -l
          env

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: OMA v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: oma-*.tar.gz
          body: |
            Optimized Mysqldump Archiver v${{ env.VERSION }}
