---
name: Test and Lint
on:
  - push
jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y default-mysql-server flake8 python3-pytest zip
          sudo .github/scripts/setup_mysql.sh

      - name: Lint with flake8
        run: |
          flake8 -v .

      - name: Test with pytest
        run: |
          sudo python3 -m pytest tests/ -v -s
